server:
  port: 8080
spring:
  profiles:
    include: oauth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://everyclub-rds.cijbaereps1o.ap-northeast-2.rds.amazonaws.com:3306/everyclub?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: rlatngus11
  thymeleaf:
    cache: false
    check-template-location: true
    prefix=classpath: /templates/
    suffix: .html
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


springdoc:
  swagger-ui:
    enabled: true # swagger ui 사용여부 (굳이 설정하지 않아도 default는 true)
  version: 'v0.0.1' # API 문서 버전
  default-consumes-media-type: application/json # 기본 consume media type
  default-produces-media-type: application/json # 기본 produce media type
  model-and-view-allowed: true # ModelAndView 허용